-- 此 CLP 文件是使用 DB2LOOK 版本 "10.1" 创建的 
-- 时间戳记: 2017/6/16 11:09:51
-- 数据库名称: PAEMS          
-- 数据库管理器版本: DB2/NT64 Version 10.1.0       
-- 数据库代码页: 1386
-- 数据库整理顺序为: UNIQUE


CONNECT TO PAEMS USER HDMS;

------------------------------------------------
-- 模式的 DDL 语句
------------------------------------------------


CREATE SCHEMA "HDMS    " AUTHORIZATION "HDMS    ";



------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."AUTH_TEST"
------------------------------------------------
 

CREATE TABLE "HDMS    "."AUTH_TEST"  (
		  "TESTID" VARCHAR(32) NOT NULL , 
		  "GROUP_ID" VARCHAR(32) NOT NULL , 
		  "TESTNAME" VARCHAR(64) NOT NULL , 
		  "TESTGROUP" VARCHAR(10) , 
		  "DEPT_ID" VARCHAR(32) )   
		 IN "USERSPACE1" ; 

COMMENT ON TABLE "HDMS    "."AUTH_TEST" IS '测试表';

COMMENT ON COLUMN "HDMS    "."AUTH_TEST"."GROUP_ID" IS '组编号';

COMMENT ON COLUMN "HDMS    "."AUTH_TEST"."TESTGROUP" IS '组名称';

COMMENT ON COLUMN "HDMS    "."AUTH_TEST"."TESTID" IS '测试编号3';

COMMENT ON COLUMN "HDMS    "."AUTH_TEST"."TESTNAME" IS '测试名称';


-- 表上主键的 DDL 语句 "HDMS    "."AUTH_TEST"

ALTER TABLE "HDMS    "."AUTH_TEST" 
	ADD PRIMARY KEY
		("TESTID",
		 "GROUP_ID");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."AUTH_MENU"
------------------------------------------------
 

CREATE TABLE "HDMS    "."AUTH_MENU"  (
		  "MENUID" VARCHAR(32) NOT NULL , 
		  "NAME" VARCHAR(64) NOT NULL , 
		  "MENU_POS" VARCHAR(20) , 
		  "HREF" VARCHAR(512) , 
		  "ICON_CLS" VARCHAR(512) , 
		  "DISPLAY" VARCHAR(3) , 
		  "ORDER_NUM" VARCHAR(11) , 
		  "PID" VARCHAR(32) , 
		  "LEVEL_TYPE" VARCHAR(30) )   
		 IN "USERSPACE1" ; 

COMMENT ON TABLE "HDMS    "."AUTH_MENU" IS '系统菜单';

COMMENT ON COLUMN "HDMS    "."AUTH_MENU"."DISPLAY" IS '是否显示';

COMMENT ON COLUMN "HDMS    "."AUTH_MENU"."HREF" IS '链接地址';

COMMENT ON COLUMN "HDMS    "."AUTH_MENU"."ICON_CLS" IS '菜单图标';

COMMENT ON COLUMN "HDMS    "."AUTH_MENU"."LEVEL_TYPE" IS '菜单类别';

COMMENT ON COLUMN "HDMS    "."AUTH_MENU"."MENU_POS" IS '菜单位置';

COMMENT ON COLUMN "HDMS    "."AUTH_MENU"."MENUID" IS '菜单编号';

COMMENT ON COLUMN "HDMS    "."AUTH_MENU"."NAME" IS '菜单名称';

COMMENT ON COLUMN "HDMS    "."AUTH_MENU"."ORDER_NUM" IS '序号';

COMMENT ON COLUMN "HDMS    "."AUTH_MENU"."PID" IS '父菜单编号';


-- 表上主键的 DDL 语句 "HDMS    "."AUTH_MENU"

ALTER TABLE "HDMS    "."AUTH_MENU" 
	ADD PRIMARY KEY
		("MENUID");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."SYS_TABLES"
------------------------------------------------
 

CREATE TABLE "HDMS    "."SYS_TABLES"  (
		  "TABLE_NAME" VARCHAR(128) NOT NULL , 
		  "SCHEMA_NAME" VARCHAR(128) NOT NULL , 
		  "TYPE" VARCHAR(30) NOT NULL , 
		  "FID" SMALLINT NOT NULL , 
		  "KEYCOLUMNS" SMALLINT , 
		  "CTIME" TIMESTAMP NOT NULL , 
		  "REMARKS" VARCHAR(254) , 
		  "GENERATE" VARCHAR(3) , 
		  "GENTYPE" VARCHAR(32) , 
		  "GTIME" TIMESTAMP , 
		  "PATH" VARCHAR(32) NOT NULL , 
		  "MENU_NAME" VARCHAR(60) , 
		  "BUSINESS_NAME" VARCHAR(20) , 
		  "DOMAIN_OBJECT_NAME" VARCHAR(40) , 
		  "VARIABLE_NAME" VARCHAR(40) , 
		  "POJO_TARGET_PACKAGE" VARCHAR(60) , 
		  "MAPPER_TARGET_PACKAGE" VARCHAR(60) , 
		  "SERVICE_TARGET_PACKAGE" VARCHAR(60) , 
		  "CONTROLLER_TARGET_PACKAGE" VARCHAR(60) , 
		  "ISADD" VARCHAR(3) , 
		  "ISUPDATE" VARCHAR(3) , 
		  "ISDELETE" VARCHAR(3) , 
		  "ID_FIELD" VARCHAR(60) , 
		  "PARENT_FIELD" VARCHAR(60) , 
		  "TREE_FIELD" VARCHAR(60) , 
		  "OPERATE_TYPE" VARCHAR(60) )   
		 IN "USERSPACE1" ; 

COMMENT ON TABLE "HDMS    "."SYS_TABLES" IS '表信息';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."BUSINESS_NAME" IS '业务包名称';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."CONTROLLER_TARGET_PACKAGE" IS 'CONTROLLER包路径';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."CTIME" IS '创建时间';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."DOMAIN_OBJECT_NAME" IS '类名称';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."FID" IS '表序号';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."GENERATE" IS '是否生成代码';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."GENTYPE" IS '生成类型';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."GTIME" IS '生成代码时间';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."ID_FIELD" IS '主键字段';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."ISADD" IS '是否可以添加';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."ISDELETE" IS '是否可以删除';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."ISUPDATE" IS '是否可以修改';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."KEYCOLUMNS" IS '主键列数量';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."MAPPER_TARGET_PACKAGE" IS 'MAPPER包路径';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."MENU_NAME" IS '菜单名称';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."OPERATE_TYPE" IS '操作页面展示类型';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."PARENT_FIELD" IS '父类字段';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."PATH" IS '访问路径';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."POJO_TARGET_PACKAGE" IS 'POJO包路径';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."REMARKS" IS '备注';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."SCHEMA_NAME" IS 'SCHEMA';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."SERVICE_TARGET_PACKAGE" IS 'SERVICE包路径';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."TABLE_NAME" IS '表名';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."TREE_FIELD" IS 'treefield';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."TYPE" IS '类型';

COMMENT ON COLUMN "HDMS    "."SYS_TABLES"."VARIABLE_NAME" IS '类对象名称';


-- 表上主键的 DDL 语句 "HDMS    "."SYS_TABLES"

ALTER TABLE "HDMS    "."SYS_TABLES" 
	ADD PRIMARY KEY
		("TABLE_NAME",
		 "SCHEMA_NAME",
		 "TYPE");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."SYS_COLUMNS"
------------------------------------------------
 

CREATE TABLE "HDMS    "."SYS_COLUMNS"  (
		  "COLNO" BIGINT NOT NULL , 
		  "COLUMN_NAME" VARCHAR(128) NOT NULL , 
		  "TBNAME" VARCHAR(128) NOT NULL , 
		  "TBCREATOR" VARCHAR(128) NOT NULL , 
		  "REMARKS" VARCHAR(254) , 
		  "COLTYPE" VARCHAR(20) NOT NULL , 
		  "PROPERTY_LENGTH" BIGINT NOT NULL , 
		  "NULLS" VARCHAR(20) NOT NULL , 
		  "PROPERTY_NAME" VARCHAR(30) , 
		  "PROPERTY_TYPE" VARCHAR(40) , 
		  "PROPERTY_TITLE" VARCHAR(40) , 
		  "ISPRIMARY" CHAR(1) , 
		  "ISSELECT" CHAR(1) , 
		  "ISLIKE" CHAR(1) , 
		  "ISDISPLAY" CHAR(1) , 
		  "ISADD" CHAR(1) , 
		  "ISUPDATE" CHAR(1) , 
		  "WIDTH" SMALLINT , 
		  "SORTABLE" CHAR(1) , 
		  "COMPONENT" VARCHAR(60) , 
		  "DATA_OPTIONS" VARCHAR(254) , 
		  "FORMATTER" VARCHAR(254) , 
		  "COMBOID" VARCHAR(32) , 
		  "DEFAULT_VALUE" VARCHAR(255) , 
		  "ORDER_NUM" VARCHAR(32) )   
		 IN "USERSPACE1" ; 

COMMENT ON TABLE "HDMS    "."SYS_COLUMNS" IS '表字段信息';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."COLNO" IS '字段序号';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."COLTYPE" IS '字段类型';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."COLUMN_NAME" IS '字段名称';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."COMBOID" IS '字典编号';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."COMPONENT" IS 'easyui控件';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."DATA_OPTIONS" IS 'data-options';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."DEFAULT_VALUE" IS '默认值';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."FORMATTER" IS '格式化';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."ISADD" IS '添加时显示';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."ISDISPLAY" IS '表格中显示';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."ISLIKE" IS '模糊查询';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."ISPRIMARY" IS '是否为主键';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."ISSELECT" IS '精确查询';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."ISUPDATE" IS '修改时显示';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."NULLS" IS '是否为空';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."ORDER_NUM" IS '序号';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."PROPERTY_LENGTH" IS '字段长度';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."PROPERTY_NAME" IS '属性名';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."PROPERTY_TITLE" IS '属性标题';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."PROPERTY_TYPE" IS '属性类型';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."REMARKS" IS '备注';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."SORTABLE" IS '允许排序';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."TBCREATOR" IS '创建用户';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."TBNAME" IS '表名称';

COMMENT ON COLUMN "HDMS    "."SYS_COLUMNS"."WIDTH" IS '宽度';


-- 表上主键的 DDL 语句 "HDMS    "."SYS_COLUMNS"

ALTER TABLE "HDMS    "."SYS_COLUMNS" 
	ADD PRIMARY KEY
		("COLUMN_NAME",
		 "TBNAME",
		 "TBCREATOR");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."SYS_COMBO_BOX"
------------------------------------------------
 

CREATE TABLE "HDMS    "."SYS_COMBO_BOX"  (
		  "COMBOID" VARCHAR(32) NOT NULL , 
		  "NAME" VARCHAR(64) NOT NULL , 
		  "TABLE_NAME" VARCHAR(128) NOT NULL , 
		  "VALUE_FIELD" VARCHAR(128) NOT NULL , 
		  "TEXT_FIELD" VARCHAR(128) NOT NULL , 
		  "WHERE_CONDITION" VARCHAR(128) , 
		  "PARENT_FIELD" VARCHAR(128) , 
		  "ROOT_VALUE" VARCHAR(128) )   
		 IN "USERSPACE1" ; 

COMMENT ON TABLE "HDMS    "."SYS_COMBO_BOX" IS '生成代码字典';

COMMENT ON COLUMN "HDMS    "."SYS_COMBO_BOX"."COMBOID" IS '字典编号';

COMMENT ON COLUMN "HDMS    "."SYS_COMBO_BOX"."NAME" IS '字典名称';

COMMENT ON COLUMN "HDMS    "."SYS_COMBO_BOX"."PARENT_FIELD" IS 'parentField';

COMMENT ON COLUMN "HDMS    "."SYS_COMBO_BOX"."ROOT_VALUE" IS '根节点值';

COMMENT ON COLUMN "HDMS    "."SYS_COMBO_BOX"."TABLE_NAME" IS '查询表';

COMMENT ON COLUMN "HDMS    "."SYS_COMBO_BOX"."TEXT_FIELD" IS 'textField';

COMMENT ON COLUMN "HDMS    "."SYS_COMBO_BOX"."VALUE_FIELD" IS 'valueField';

COMMENT ON COLUMN "HDMS    "."SYS_COMBO_BOX"."WHERE_CONDITION" IS '查询条件(key:value)';


-- 表上主键的 DDL 语句 "HDMS    "."SYS_COMBO_BOX"

ALTER TABLE "HDMS    "."SYS_COMBO_BOX" 
	ADD PRIMARY KEY
		("COMBOID");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."AUTH_USER"
------------------------------------------------
 

CREATE TABLE "HDMS    "."AUTH_USER"  (
		  "USERID" VARCHAR(32) NOT NULL , 
		  "USERNAME" VARCHAR(32) NOT NULL , 
		  "OPERATORNAME" VARCHAR(40) NOT NULL , 
		  "PASSWORD" VARCHAR(50) NOT NULL , 
		  "CREATETIME" TIMESTAMP NOT NULL , 
		  "ALTERTIME" TIMESTAMP NOT NULL , 
		  "STATUS" VARCHAR(20) NOT NULL )   
		 IN "USERSPACE1" ; 

COMMENT ON TABLE "HDMS    "."AUTH_USER" IS '操作员信息';

COMMENT ON COLUMN "HDMS    "."AUTH_USER"."ALTERTIME" IS '更新时间';

COMMENT ON COLUMN "HDMS    "."AUTH_USER"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "HDMS    "."AUTH_USER"."OPERATORNAME" IS '操作员名称';

COMMENT ON COLUMN "HDMS    "."AUTH_USER"."PASSWORD" IS '操作员密码';

COMMENT ON COLUMN "HDMS    "."AUTH_USER"."STATUS" IS '用户状态';

COMMENT ON COLUMN "HDMS    "."AUTH_USER"."USERID" IS '用户编号';

COMMENT ON COLUMN "HDMS    "."AUTH_USER"."USERNAME" IS '登录用户账号';


-- 表上主键的 DDL 语句 "HDMS    "."AUTH_USER"

ALTER TABLE "HDMS    "."AUTH_USER" 
	ADD PRIMARY KEY
		("USERID");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."AUTH_ROLE"
------------------------------------------------
 

CREATE TABLE "HDMS    "."AUTH_ROLE"  (
		  "ROLEID" VARCHAR(32) NOT NULL , 
		  "NAME" VARCHAR(64) NOT NULL , 
		  "TYPE" VARCHAR(64) )   
		 IN "USERSPACE1" ; 

COMMENT ON TABLE "HDMS    "."AUTH_ROLE" IS '角色表';

COMMENT ON COLUMN "HDMS    "."AUTH_ROLE"."NAME" IS '角色名称';

COMMENT ON COLUMN "HDMS    "."AUTH_ROLE"."ROLEID" IS '角色编号';

COMMENT ON COLUMN "HDMS    "."AUTH_ROLE"."TYPE" IS '角色类型';


-- 表上主键的 DDL 语句 "HDMS    "."AUTH_ROLE"

ALTER TABLE "HDMS    "."AUTH_ROLE" 
	ADD PRIMARY KEY
		("ROLEID");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."SYS_DICT_TYPE"
------------------------------------------------
 

CREATE TABLE "HDMS    "."SYS_DICT_TYPE"  (
		  "DICTTYPEID" VARCHAR(128) NOT NULL , 
		  "DICTTYPENAME" VARCHAR(255) , 
		  "RANK" CHAR(1) , 
		  "PARENTID" VARCHAR(255) )   
		 IN "USERSPACE1" ; 

COMMENT ON TABLE "HDMS    "."SYS_DICT_TYPE" IS '数据字典';

COMMENT ON COLUMN "HDMS    "."SYS_DICT_TYPE"."DICTTYPEID" IS '字典编号';

COMMENT ON COLUMN "HDMS    "."SYS_DICT_TYPE"."DICTTYPENAME" IS '字典名称';

COMMENT ON COLUMN "HDMS    "."SYS_DICT_TYPE"."PARENTID" IS '上级编号';

COMMENT ON COLUMN "HDMS    "."SYS_DICT_TYPE"."RANK" IS '字典等级';


-- 表上主键的 DDL 语句 "HDMS    "."SYS_DICT_TYPE"

ALTER TABLE "HDMS    "."SYS_DICT_TYPE" 
	ADD PRIMARY KEY
		("DICTTYPEID");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."SYS_DICT_ENTRY"
------------------------------------------------
 

CREATE TABLE "HDMS    "."SYS_DICT_ENTRY"  (
		  "DICTTYPEID" VARCHAR(128) NOT NULL , 
		  "DICTID" VARCHAR(128) NOT NULL , 
		  "DICTNAME" VARCHAR(255) , 
		  "STATUS" VARCHAR(3) , 
		  "SORTNO" INTEGER , 
		  "RANK" CHAR(1) , 
		  "PARENTID" VARCHAR(255) )   
		 IN "USERSPACE1" ; 

COMMENT ON TABLE "HDMS    "."SYS_DICT_ENTRY" IS '数据字典';

COMMENT ON COLUMN "HDMS    "."SYS_DICT_ENTRY"."DICTID" IS '字典项编号';

COMMENT ON COLUMN "HDMS    "."SYS_DICT_ENTRY"."DICTNAME" IS '字典项名称';

COMMENT ON COLUMN "HDMS    "."SYS_DICT_ENTRY"."DICTTYPEID" IS '字典编号';

COMMENT ON COLUMN "HDMS    "."SYS_DICT_ENTRY"."PARENTID" IS '上级编号';

COMMENT ON COLUMN "HDMS    "."SYS_DICT_ENTRY"."RANK" IS '字典等级';

COMMENT ON COLUMN "HDMS    "."SYS_DICT_ENTRY"."SORTNO" IS '序号';

COMMENT ON COLUMN "HDMS    "."SYS_DICT_ENTRY"."STATUS" IS '状态';


-- 表上主键的 DDL 语句 "HDMS    "."SYS_DICT_ENTRY"

ALTER TABLE "HDMS    "."SYS_DICT_ENTRY" 
	ADD PRIMARY KEY
		("DICTTYPEID",
		 "DICTID");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."AUTH_ROLE_MENU"
------------------------------------------------
 

CREATE TABLE "HDMS    "."AUTH_ROLE_MENU"  (
		  "ROLE_MENU_ID" VARCHAR(32) NOT NULL , 
		  "ROLE_ID" VARCHAR(32) NOT NULL , 
		  "MENU_ID" VARCHAR(32) NOT NULL )   
		 IN "USERSPACE1" ; 


-- 表上主键的 DDL 语句 "HDMS    "."AUTH_ROLE_MENU"

ALTER TABLE "HDMS    "."AUTH_ROLE_MENU" 
	ADD PRIMARY KEY
		("ROLE_MENU_ID");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."AUTH_USER_ROLE"
------------------------------------------------
 

CREATE TABLE "HDMS    "."AUTH_USER_ROLE"  (
		  "USER_ROLE_ID" VARCHAR(32) NOT NULL , 
		  "USER_ID" VARCHAR(32) NOT NULL , 
		  "ROLE_ID" VARCHAR(32) NOT NULL )   
		 IN "USERSPACE1" ; 


-- 表上主键的 DDL 语句 "HDMS    "."AUTH_USER_ROLE"

ALTER TABLE "HDMS    "."AUTH_USER_ROLE" 
	ADD PRIMARY KEY
		("USER_ROLE_ID");


------------------------------------------------
-- 表的 DDL 语句 "111111  "."CMS_ARTICLE"
------------------------------------------------
 

CREATE TABLE "111111  "."CMS_ARTICLE"  (
		  "ARTICLE_ID" VARCHAR(32) )   
		 IN "USERSPACE1" ; 

ALTER TABLE "111111  "."CMS_ARTICLE" PCTFREE 0;





------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."CMS_ARTICLE"
------------------------------------------------
 

CREATE TABLE "HDMS    "."CMS_ARTICLE"  (
		  "ARTICLE_ID" VARCHAR(32) NOT NULL , 
		  "TITLE" VARCHAR(255) , 
		  "CONTENT" CLOB(1048576) NOT LOGGED NOT COMPACT , 
		  "CHANNEL_ID" VARCHAR(32) , 
		  "THUMBNAIL" VARCHAR(255) , 
		  "KEYWORDS" VARCHAR(255) , 
		  "DESCRIPTION" VARCHAR(500) , 
		  "CREATETIME" TIMESTAMP , 
		  "USERID" VARCHAR(32) , 
		  "READ_COUNT" INTEGER , 
		  "STATUS" VARCHAR(10) )   
		 IN "USERSPACE1" ; 

ALTER TABLE "HDMS    "."CMS_ARTICLE" PCTFREE 0;

COMMENT ON COLUMN "HDMS    "."CMS_ARTICLE"."ARTICLE_ID" IS '文章编号';

COMMENT ON COLUMN "HDMS    "."CMS_ARTICLE"."CHANNEL_ID" IS '栏目编号';

COMMENT ON COLUMN "HDMS    "."CMS_ARTICLE"."CONTENT" IS '文章内容';

COMMENT ON COLUMN "HDMS    "."CMS_ARTICLE"."CREATETIME" IS '发布时间';

COMMENT ON COLUMN "HDMS    "."CMS_ARTICLE"."DESCRIPTION" IS '文章描述';

COMMENT ON COLUMN "HDMS    "."CMS_ARTICLE"."KEYWORDS" IS '关键字';

COMMENT ON COLUMN "HDMS    "."CMS_ARTICLE"."READ_COUNT" IS '已读数量';

COMMENT ON COLUMN "HDMS    "."CMS_ARTICLE"."STATUS" IS '状态';

COMMENT ON COLUMN "HDMS    "."CMS_ARTICLE"."THUMBNAIL" IS '缩略图';

COMMENT ON COLUMN "HDMS    "."CMS_ARTICLE"."TITLE" IS '文章标题';

COMMENT ON COLUMN "HDMS    "."CMS_ARTICLE"."USERID" IS '用户编号';


-- 表上主键的 DDL 语句 "HDMS    "."CMS_ARTICLE"

ALTER TABLE "HDMS    "."CMS_ARTICLE" 
	ADD PRIMARY KEY
		("ARTICLE_ID");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."CMS_BANNER"
------------------------------------------------
 

CREATE TABLE "HDMS    "."CMS_BANNER"  (
		  "BANNER_ID" VARCHAR(32) NOT NULL , 
		  "BANNER_TITLE" VARCHAR(32) , 
		  "TYPE" VARCHAR(255) , 
		  "IMG" VARCHAR(255) , 
		  "CREATETIME" TIMESTAMP , 
		  "ORDER_NUM" INTEGER )   
		 IN "USERSPACE1" ; 

ALTER TABLE "HDMS    "."CMS_BANNER" PCTFREE 0;

COMMENT ON COLUMN "HDMS    "."CMS_BANNER"."BANNER_ID" IS '编号';

COMMENT ON COLUMN "HDMS    "."CMS_BANNER"."BANNER_TITLE" IS '标题';

COMMENT ON COLUMN "HDMS    "."CMS_BANNER"."CREATETIME" IS '创建时间';

COMMENT ON COLUMN "HDMS    "."CMS_BANNER"."IMG" IS '图片';

COMMENT ON COLUMN "HDMS    "."CMS_BANNER"."ORDER_NUM" IS '序号';

COMMENT ON COLUMN "HDMS    "."CMS_BANNER"."TYPE" IS '类型';


-- 表上主键的 DDL 语句 "HDMS    "."CMS_BANNER"

ALTER TABLE "HDMS    "."CMS_BANNER" 
	ADD PRIMARY KEY
		("BANNER_ID");


------------------------------------------------
-- 表的 DDL 语句 "HDMS    "."CMS_CHANNEL"
------------------------------------------------
 

CREATE TABLE "HDMS    "."CMS_CHANNEL"  (
		  "CHANNEL_ID" VARCHAR(32) NOT NULL , 
		  "CHANNEL_NAME" VARCHAR(64) , 
		  "CHANNEL_SORT" INTEGER , 
		  "ISTOP" VARCHAR(3) , 
		  "CHANNEL_TYPE" VARCHAR(32) , 
		  "PID" VARCHAR(32) , 
		  "CREATETIME" TIMESTAMP , 
		  "URL" VARCHAR(255) , 
		  "STATUS" VARCHAR(3) , 
		  "CONTENT" CLOB(1048576) NOT LOGGED NOT COMPACT )   
		 IN "USERSPACE1" ; 

ALTER TABLE "HDMS    "."CMS_CHANNEL" PCTFREE 0;

COMMENT ON COLUMN "HDMS    "."CMS_CHANNEL"."CHANNEL_ID" IS '栏目编号';

COMMENT ON COLUMN "HDMS    "."CMS_CHANNEL"."CHANNEL_NAME" IS '栏目名称';

COMMENT ON COLUMN "HDMS    "."CMS_CHANNEL"."CHANNEL_SORT" IS '排列顺序';

COMMENT ON COLUMN "HDMS    "."CMS_CHANNEL"."CHANNEL_TYPE" IS '栏目类型';

COMMENT ON COLUMN "HDMS    "."CMS_CHANNEL"."CONTENT" IS '栏目内容';

COMMENT ON COLUMN "HDMS    "."CMS_CHANNEL"."CREATETIME" IS '发布时间';

COMMENT ON COLUMN "HDMS    "."CMS_CHANNEL"."ISTOP" IS '顶级栏目';

COMMENT ON COLUMN "HDMS    "."CMS_CHANNEL"."PID" IS '上级栏目编号';

COMMENT ON COLUMN "HDMS    "."CMS_CHANNEL"."STATUS" IS '状态';

COMMENT ON COLUMN "HDMS    "."CMS_CHANNEL"."URL" IS '链接地址';


-- 表上主键的 DDL 语句 "HDMS    "."CMS_CHANNEL"

ALTER TABLE "HDMS    "."CMS_CHANNEL" 
	ADD PRIMARY KEY
		("CHANNEL_ID");









-- 公用同义词的 DDL 语句

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_ALL_TABLES" FOR TABLE "SYSIBMADM"."ALL_ALL_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_ARGUMENTS" FOR TABLE "SYSIBMADM"."ALL_ARGUMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_CATALOG" FOR TABLE "SYSIBMADM"."ALL_CATALOG";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_COL_COMMENTS" FOR TABLE "SYSIBMADM"."ALL_COL_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_CONS_COLUMNS" FOR TABLE "SYSIBMADM"."ALL_CONS_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_CONSTRAINTS" FOR TABLE "SYSIBMADM"."ALL_CONSTRAINTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_DEPENDENCIES" FOR TABLE "SYSIBMADM"."ALL_DEPENDENCIES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_ERRORS" FOR TABLE "SYSIBMADM"."ALL_ERRORS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_IND_COLUMNS" FOR TABLE "SYSIBMADM"."ALL_IND_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_IND_PARTITIONS" FOR TABLE "SYSIBMADM"."ALL_IND_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_INDEXES" FOR TABLE "SYSIBMADM"."ALL_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_OBJECTS" FOR TABLE "SYSIBMADM"."ALL_OBJECTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_PART_INDEXES" FOR TABLE "SYSIBMADM"."ALL_PART_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_PART_KEY_COLUMNS" FOR TABLE "SYSIBMADM"."ALL_PART_KEY_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_PART_TABLES" FOR TABLE "SYSIBMADM"."ALL_PART_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_PROCEDURES" FOR TABLE "SYSIBMADM"."ALL_PROCEDURES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_SEQUENCES" FOR TABLE "SYSIBMADM"."ALL_SEQUENCES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_SOURCE" FOR TABLE "SYSIBMADM"."ALL_SOURCE";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_SYNONYMS" FOR TABLE "SYSIBMADM"."ALL_SYNONYMS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_COL_STATISTICS" FOR TABLE "SYSIBMADM"."ALL_TAB_COL_STATISTICS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_COLUMNS" FOR TABLE "SYSIBMADM"."ALL_TAB_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_COMMENTS" FOR TABLE "SYSIBMADM"."ALL_TAB_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_PARTITIONS" FOR TABLE "SYSIBMADM"."ALL_TAB_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_PRIVS" FOR TABLE "SYSIBMADM"."ALL_TAB_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_PRIVS_MADE" FOR TABLE "SYSIBMADM"."ALL_TAB_PRIVS_MADE";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TAB_PRIVS_RECD" FOR TABLE "SYSIBMADM"."ALL_TAB_PRIVS_RECD";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TABLES" FOR TABLE "SYSIBMADM"."ALL_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_TRIGGERS" FOR TABLE "SYSIBMADM"."ALL_TRIGGERS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_VIEW_COLUMNS" FOR TABLE "SYSIBMADM"."ALL_VIEW_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ALL_VIEWS" FOR TABLE "SYSIBMADM"."ALL_VIEWS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."CAT" FOR TABLE "SYSIBMADM"."USER_CATALOG";

CREATE PUBLIC ALIAS "SYSPUBLIC"."COLS" FOR TABLE "SYSIBMADM"."USER_TAB_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_ALL_TABLES" FOR TABLE "SYSIBMADM"."DBA_ALL_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_ARGUMENTS" FOR TABLE "SYSIBMADM"."DBA_ARGUMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_CATALOG" FOR TABLE "SYSIBMADM"."DBA_CATALOG";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_COL_COMMENTS" FOR TABLE "SYSIBMADM"."DBA_COL_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_CONS_COLUMNS" FOR TABLE "SYSIBMADM"."DBA_CONS_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_CONSTRAINTS" FOR TABLE "SYSIBMADM"."DBA_CONSTRAINTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_DEPENDENCIES" FOR TABLE "SYSIBMADM"."DBA_DEPENDENCIES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_ERRORS" FOR TABLE "SYSIBMADM"."DBA_ERRORS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_IND_COLUMNS" FOR TABLE "SYSIBMADM"."DBA_IND_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_IND_PARTITIONS" FOR TABLE "SYSIBMADM"."DBA_IND_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_INDEXES" FOR TABLE "SYSIBMADM"."DBA_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_OBJECTS" FOR TABLE "SYSIBMADM"."DBA_OBJECTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_PART_INDEXES" FOR TABLE "SYSIBMADM"."DBA_PART_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_PART_KEY_COLUMNS" FOR TABLE "SYSIBMADM"."DBA_PART_KEY_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_PART_TABLES" FOR TABLE "SYSIBMADM"."DBA_PART_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_PROCEDURES" FOR TABLE "SYSIBMADM"."DBA_PROCEDURES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_ROLE_PRIVS" FOR TABLE "SYSIBMADM"."DBA_ROLE_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_ROLES" FOR TABLE "SYSIBMADM"."DBA_ROLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_SEQUENCES" FOR TABLE "SYSIBMADM"."DBA_SEQUENCES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_SOURCE" FOR TABLE "SYSIBMADM"."DBA_SOURCE";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_SYNONYMS" FOR TABLE "SYSIBMADM"."DBA_SYNONYMS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_SYS_PRIVS" FOR TABLE "SYSIBMADM"."DBA_SYS_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TAB_COL_STATISTICS" FOR TABLE "SYSIBMADM"."DBA_TAB_COL_STATISTICS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TAB_COLUMNS" FOR TABLE "SYSIBMADM"."DBA_TAB_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TAB_COMMENTS" FOR TABLE "SYSIBMADM"."DBA_TAB_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TAB_PARTITIONS" FOR TABLE "SYSIBMADM"."DBA_TAB_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TAB_PRIVS" FOR TABLE "SYSIBMADM"."DBA_TAB_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TABLES" FOR TABLE "SYSIBMADM"."DBA_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TABLESPACES" FOR TABLE "SYSIBMADM"."DBA_TABLESPACES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_TRIGGERS" FOR TABLE "SYSIBMADM"."DBA_TRIGGERS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_VIEW_COLUMNS" FOR TABLE "SYSIBMADM"."DBA_VIEW_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DBA_VIEWS" FOR TABLE "SYSIBMADM"."DBA_VIEWS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DICT" FOR TABLE "SYSIBMADM"."DICTIONARY";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DICT_COLUMNS" FOR TABLE "SYSIBMADM"."DICT_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."DICTIONARY" FOR TABLE "SYSIBMADM"."DICTIONARY";

CREATE PUBLIC ALIAS "SYSPUBLIC"."IND" FOR TABLE "SYSIBMADM"."USER_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."OBJ" FOR TABLE "SYSIBMADM"."USER_OBJECTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ROLE_ROLE_PRIVS" FOR TABLE "SYSIBMADM"."ROLE_ROLE_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ROLE_SYS_PRIVS" FOR TABLE "SYSIBMADM"."ROLE_SYS_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."ROLE_TAB_PRIVS" FOR TABLE "SYSIBMADM"."ROLE_TAB_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."SEQ" FOR TABLE "SYSIBMADM"."USER_SEQUENCES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."SESSION_PRIVS" FOR TABLE "SYSIBMADM"."SESSION_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."SESSION_ROLES" FOR TABLE "SYSIBMADM"."SESSION_ROLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."SIN" FOR TABLE "SYSIBMADM"."USER_SYNONYMS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."TAB" FOR TABLE "SYSIBMADM"."TAB";

CREATE PUBLIC ALIAS "SYSPUBLIC"."TABS" FOR TABLE "SYSIBMADM"."USER_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_ALL_TABLES" FOR TABLE "SYSIBMADM"."USER_ALL_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_ARGUMENTS" FOR TABLE "SYSIBMADM"."USER_ARGUMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_CATALOG" FOR TABLE "SYSIBMADM"."USER_CATALOG";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_COL_COMMENTS" FOR TABLE "SYSIBMADM"."USER_COL_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_CONS_COLUMNS" FOR TABLE "SYSIBMADM"."USER_CONS_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_CONSTRAINTS" FOR TABLE "SYSIBMADM"."USER_CONSTRAINTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_DEPENDENCIES" FOR TABLE "SYSIBMADM"."USER_DEPENDENCIES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_ERRORS" FOR TABLE "SYSIBMADM"."USER_ERRORS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_IND_COLUMNS" FOR TABLE "SYSIBMADM"."USER_IND_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_IND_PARTITIONS" FOR TABLE "SYSIBMADM"."USER_IND_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_INDEXES" FOR TABLE "SYSIBMADM"."USER_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_OBJECTS" FOR TABLE "SYSIBMADM"."USER_OBJECTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_PART_INDEXES" FOR TABLE "SYSIBMADM"."USER_PART_INDEXES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_PART_KEY_COLUMNS" FOR TABLE "SYSIBMADM"."USER_PART_KEY_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_PART_TABLES" FOR TABLE "SYSIBMADM"."USER_PART_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_PROCEDURES" FOR TABLE "SYSIBMADM"."USER_PROCEDURES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_ROLE_PRIVS" FOR TABLE "SYSIBMADM"."USER_ROLE_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_SEQUENCES" FOR TABLE "SYSIBMADM"."USER_SEQUENCES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_SOURCE" FOR TABLE "SYSIBMADM"."USER_SOURCE";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_SYNONYMS" FOR TABLE "SYSIBMADM"."USER_SYNONYMS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_SYS_PRIVS" FOR TABLE "SYSIBMADM"."USER_SYS_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_COL_STATISTICS" FOR TABLE "SYSIBMADM"."USER_TAB_COL_STATISTICS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_COLUMNS" FOR TABLE "SYSIBMADM"."USER_TAB_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_COMMENTS" FOR TABLE "SYSIBMADM"."USER_TAB_COMMENTS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_PARTITIONS" FOR TABLE "SYSIBMADM"."USER_TAB_PARTITIONS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_PRIVS" FOR TABLE "SYSIBMADM"."USER_TAB_PRIVS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_PRIVS_MADE" FOR TABLE "SYSIBMADM"."USER_TAB_PRIVS_MADE";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TAB_PRIVS_RECD" FOR TABLE "SYSIBMADM"."USER_TAB_PRIVS_RECD";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TABLES" FOR TABLE "SYSIBMADM"."USER_TABLES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TABLESPACES" FOR TABLE "SYSIBMADM"."USER_TABLESPACES";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_TRIGGERS" FOR TABLE "SYSIBMADM"."USER_TRIGGERS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_VIEW_COLUMNS" FOR TABLE "SYSIBMADM"."USER_VIEW_COLUMNS";

CREATE PUBLIC ALIAS "SYSPUBLIC"."USER_VIEWS" FOR TABLE "SYSIBMADM"."USER_VIEWS";


COMMIT WORK;

CONNECT RESET;

TERMINATE;

